---
- name: copy counter-panda app
  copy: src=counter-panda-app dest=/root/ owner=root group=root mode=0755

- name: npm install
  npm: path=/root/counter-panda-app

- name: restarts service
  command: /root/counter-panda-app/service.sh restart
